Project.toml
src/NavAbilitySDK.jl
src/navability/entities/Distributions.jl
src/navability/entities/Factor.jl
src/navability/entities/InferenceTypes.jl
test/runtests.jl
test/unit/runtests.jl
test/unit/testDistributions.jl
test/unit/testFactors.jl

Strongly opinionated changes to remove drift and align the SDK to the same pattern as the Python SDK. This is required to complete the remaining work for 0.4.x.
- Refactored to introduce a container for function data, i.e. InferenceType
- Added the new distributions to resolve #67 
- Added the start of unit tests
- Added the start of documentation

Refactoring and adding new distribution functions.

---

Project.toml
src/NavAbilitySDK.jl
src/navability/entities/Distributions.jl
src/navability/entities/Factor.jl
src/navability/entities/InferenceTypes.jl
test/runtests.jl
test/unit/runtests.jl
test/unit/testDistributions.jl
test/unit/testFactors.jl

Adding the factor types needed for the tutorials:
- Resolves #68 
- Resolves #69 
- Resolves #70

Pose2Point2BearingRange, PriorPoint2, Point2Point2Range

---

src/NavAbilitySDK.jl
src/navability/entities/Factor.jl
src/navability/entities/InferenceTypes.jl
test/unit/testFactors.jl

LinearRelative, Mixture, and Prior

---

src/NavAbilitySDK.jl
src/navability/entities/Client.jl
src/navability/entities/StatusMessage.jl
src/navability/graphql/Status.jl
src/navability/services/Factor.jl
src/navability/services/Solve.jl
src/navability/services/Status.jl
src/navability/services/Utils.jl
src/navability/services/Variable.jl
test/integration/fixtures.jl
test/integration/runtests.jl
test/integration/testFactor.jl
test/integration/testSolve.jl
test/integration/testVariable.jl

Status messages, `waitForCompletion`, and refactored tests to make them expandable for more complex graphs.
Resolves #80 and prepares the codebase for #79 and #81.

[WIP] Statuses, `waitForCompletion`, and code+test cleanup

---

src/navability/entities/NavAbilityClient.jl

close #84
----
Keep in mind a future improvement will be needed:
- https://github.com/NavAbility/NavAbilitySDK.jl/issues/84#issuecomment-1082544003

Lazy apiUrl

---

.github/workflows/slack-announce.yml

@dehann merge whenever works for you.

Adding the Slack release announcement

---

src/navability/entities/Factor.jl

I just did it the same way as `certainhypo` for now.

Fix multihypo Int->Float64 & populate with Factor

---

Project.toml
src/navability/entities/NavAbilityClient.jl
test/integration/runtests.jl

Updating default URL

---

src/navability/entities/NavAbilityClient.jl
src/navability/services/Status.jl

For building Tut5.  At least auth is not hard coded anywhere.  Also, this auth will not be shown to public via tutorials.  Just needed to upload the 100s of datablobs for Tut5
also a bug fix on getStatus

auth token via stdin (or getpass)

---

.github/workflows/tests.yml
docs/Project.toml
docs/make.jl
docs/src/index.md

Add docs with Documenter

---

src/NavAbilitySDK.jl
src/navability/entities/Solve.jl
src/navability/graphql/QueriesDeprecated.jl
src/navability/services/Solve.jl
test/integration/testSolve.jl

Adds SolveOptions for solve keys and parametric solving.
Resolve #137

Adding SolveOptions to solveSession call

---

test/integration/testSolve.jl

Restore parametric solve test

---

test/integration/testFactor.jl

I missed the commit, to close https://github.com/NavAbility/NavAbilitySDK.jl/issues/160

test deleteFactor

---

Makefile
src/navability/graphql/Status.jl
src/navability/services/Variable.jl
test/integration/runtests.jl
test/integration/testInitVariable.jl

Trying to restore failing test relating to initVariable.  Need help to restore please.

restore initVariable test

---

src/navability/graphql/Factor.jl
test/integration/testFactor.jl

trying to restore the deleteFactor test.

restore deleteFactor test

---

Project.toml
src/Deprecated.jl
src/NavAbilitySDK.jl
src/navability/graphql/Variable.jl
src/navability/services/Variable.jl
test/integration/testVariable.jl

Adding `addVariablePacked` and `updateVariablePacked`.
```julia
using Revise
using NavAbilitySDK
using IncrementalInference
using RoME
using DistributedFactorGraphs
memFg = initfg()
v = IncrementalInference.addVariable!(memFg, :x0, Pose2)
v = IncrementalInference.addVariable!(memFg, :x1, Pose2)
client = NavAbilityHttpsClient()
context = Client(
"guest@navability.io",
"TestAdd",
"TestAdd")
NavAbilitySDK.ls(client, context) |> fetch
packedVariable = packVariable(memFg, v)
eventId = addVariablePacked(client, context, packedVariable) |> fetch
NavAbilitySDK.getStatusLatest(client, eventId) |> fetch
v = NavAbilitySDK.getVariable(client, context, "x1") |> fetch
push!(v["tags"], "TEST")
eventId = updateVariablePacked(client, context, v) |> fetch
NavAbilitySDK.getStatusLatest(client, eventId) |> …
```

New functions for adding and updating packed variables 

---

src/navability/entities/NavAbilityClient.jl

Additional debugging and randomizing the backoff times.

Request logging and randomized backoff time.

---

src/navability/services/DataBlobs.jl

use instead listBlobs getBlob

---

src/navability/graphql/DataBlobs.jl
src/navability/services/DataBlobs.jl
src/navability/services/Variable.jl

@dehann if you can take a look so far if it's on the right path? I just made it fit the existing structure and it's adding entries again.
I see the pattern for events is different, but wanted to take a small step to just get it working again. I'll test some more when I get a chance.

First pass on fixing adding blob entry

---

src/navability/services/DataBlobs.jl

getBlob as Vec{UInt8} not IO

---

Project.toml
src/navability/graphql/Factor.jl
src/navability/services/Factor.jl

FYI on legacy improvement @Affie

query side listFactors
